config/routes.rb
Rails.application.routes.draw do
  get 'fa_qs/index'
  get 'press/index'
  get 'galleries/index'
  get 'contacts/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'dashboards#index'
  get 'dashboards/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bfooter.rb
class Bfooter < ApplicationRecord
		has_one_attached :image
end

app/models/dashboard_image.rb
class DashboardImage < ApplicationRecord
	
end

app/models/footer.rb
class Footer < ApplicationRecord
	has_one_attached :image
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	has_one_attached :image
	enum size:[:size570x200,:size570x430]
end

app/models/jbottoum.rb
class Jbottoum < ApplicationRecord
	has_one_attached :image
end

app/models/jumbotron.rb
class Jumbotron < ApplicationRecord
	has_one_attached :image
end

app/models/pakage.rb
class Pakage < ApplicationRecord
	has_one_attached :image
end

app/models/press.rb
class Press < ApplicationRecord
	has_one_attached :image
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
	end	
end

app/controllers/fa_qs_controller.rb
class FaQsController < ApplicationController
  def index
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
  	@pictures = Gallery.all
  end
end

app/controllers/press_controller.rb
class PressController < ApplicationController
  def index
  	@presses = Press.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/fa_qs_helper.rb
module FaQsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/press_helper.rb
module PressHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotelplaza</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="" />
  <meta name="keywords" content="" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body itemscope>
  <div class="theme-layout">
    <div class="header-container" style="position: sticky;top: 0px;">
      <div class="topbar">
        <div class="weather-wrapper">
          <div id="weather"></div>
        </div>
        <span class="address"><i class="fa fa-map-marker"></i> Av. República de Uruguay 570 Huancayo
        </span>
      </div><!-- Topbar -->
      <header>
        <div class="container" style="margin-right: 5%">
          <div class="logo-sec" id="hotelicon">
          
            <a href="/dashboards/index"><%=image_tag "logo.png"%></a>
          </div><!-- logo -->
          <nav style="float: right"> 
            <ul>
              <li class="menu-item-has-children"><%= link_to 'Gallery' ,galleries_index_path, style:"text-decoration: none"%>
              </li>
              <li class="menu-item-has-children" style="text-decoration: none"><%= link_to "Press",  press_index_path , style:"text-decoration: none"%>
              </li>
              <li class="menu-item-has-children" style="text-decoration: none"><%= link_to "Contacts",contacts_index_path, style:"text-decoration: none"%>
              </li>
              <li class="menu-item-has-children" style="text-decoration: none"><%= link_to "FAQs",fa_qs_index_path, style:"text-decoration: none"%>
              </li>
              
            </ul>
          </nav><!-- nav -->
          <a class="book-now call-popup" id="book-now-btn2" href="#" title="" style="text-decoration: none">Book Now</a>
          <span class="responsive-btn"><a href="#" title=""><i class="fa fa-align-center"></i></a></span>
        </div>
      </header><!-- Header -->

      <div class="responsive-menu">
        <ul>
          <li class="menu-item-has-children"><%= link_to 'Gallery' ,galleries_index_path, style:"text-decoration: none"%>
              </li>
          <li class="menu-item-has-children"><%= link_to "Press",  press_index_path , style:"text-decoration: none"%></a>
              </li>
          <li class="menu-item-has-children"><%= link_to "Contacts",contacts_index_path, style:"text-decoration: none"%>
              </li>
          <li class="menu-item-has-children"><%= link_to "FAQs",fa_qs_index_path, style:"text-decoration: none"%>
              </li>
        </ul>
        
      </div><!-- Responsive Menu -->
    </div><!-- Header Container -->


    <%= yield %>

    <footer>
      <div class="block darkblue-layer">
        <div data-velocity="-.1" style="background: url(http://placehold.it/1366x768) repeat scroll 50% 0 transparent;" class="parallax"></div>
        <div class="container">
          <div class="footer-widgets">
            <div class="row">
              <div class="col-md-4">
                <div class="widget">
                  <div class="about-widget">
                    <a href="#"><%= image_tag "footer-logo.png" %></a>
                    <p>Vestibulum id ligula porta felis euismod sem per. Aenean eu leo quam. Pellentesque orn are sem lacinia quam venenatis. Fusce dap ibus, tellus ac cursus commodo ut fermentu massa. mentum sit amet risus.</p>
                  </div>
                </div><!-- Widget -->
              </div>
              <!-- <div class="col-md-3">
                <div class="widget">
                  <div class="widget-title">
                    <h4>Recent News</h4>
                    <span>Blog Posts</span>
                  </div>
                  <div class="widget-news">
                    <div class="recent-news">
                      <span class="date">
                        <i>August</i><strong>25</strong>
                      </span>
                      <a href="blog-detail.html" title="">An Exceptional Hotel Template!</a>
                    </div>
                    <div class="recent-news">
                      <span class="date">
                        <i>August</i><strong>18</strong>
                      </span>
                      <a href="blog-detail.html" title="">Comfortable & Spacious Apartment</a>
                    </div>
                  </div>
                </div>
              </div> -->
              <div class="col-md-4">
                <div class="widget">
                  <div class="offers-widget">
                    <% @footers = Footer.all%>
                    <% @footers.each do |footer|%>
                    <div class="offer">
                      <%= image_tag footer.image , style:"width:370px;height:100px"%>
                      <div class="offer-overlay">
                        <span style="text-decoration: none">Couple Room</span>
                        <a href="https://sky-sa1.clock-software.com/64789/10598/wbe/products/new" title="" style="text-decoration: none">Honymoon Suite</a>
                      </div>
                    </div><!-- Offer -->
                   <%end%>
                  </div><!-- Offers Widget -->
                </div>
              </div>
              <div class="col-md-4">
                <div class="widget">
                  <div class="widget-title">
                    <h4>Luxury Offer</h4>
                    <span>Local Guide</span>
                  </div>
                  <ul>
                    <li><i class="fa fa-umbrella"></i> Boutiques</li>
                    <li><i class="fa fa-laptop"></i> Complimentary wireless internet</li>
                    <li><i class="fa fa-clock-o"></i> Private beach with service</li>
                    <li><i class="fa fa-wifi"></i> Pet-friendly resort</li>
                    <li><i class="fa fa-umbrella"></i> Tennis courts</li>
                  </ul><!-- ul -->
                </div><!-- Luxury Offers -->
              </div>
            </div>
          </div><!-- Footer Widgets -->
        </div>
      </div>
    </footer><!-- footer -->

    <div class="bottom-footer">
      <div class="container">
        <div class="contact-bar">
          <div class="col-md-4">
            <div class="contact-details">
              <span><i class="fa fa-map-marker"></i></span>
              <strong>Address:</strong>
              <p style="font-size: 11px">Av. República de Uruguay 570 Huancayo</p>
            </div><!-- contact-details -->
          </div>
          <div class="col-md-4">
            <div class="contact-details dark">
              <span><i class="fa fa-phone"></i></span>
              <strong>Call Us Now:</strong>
              <p>888-832-5258, <span>888-832-5276</span></p>
            </div><!-- contact-details -->
          </div>
          <div class="col-md-4">
            <div class="contact-details">
              <span><i class="fa fa-envelope-square"></i></span>
              <strong>Email Address:</strong>
              <p>emailyourwebsite@webinane.com</p>
            </div><!-- contact-details -->
          </div>
        </div><!-- contact-data -->
        <p>&copy; 2015 <a href="#">Resort</a> - All Rights Reserved - Made By <a href="#">Webinane</a></p>
      </div><!-- container -->
    </div><!-- after-footer -->
  </div>
  </body>
</html>